### ISSUE TITLE
Borrow code from `/calendar/lib/cal_web/live/app_live.ex` and publish to hex.pm

### ISSUE THREAD

**Issue by nelsonic** [dwyl/gcal#1]
# Todo

+ [x] Borrow the `private` functions from: https://github.com/dwyl/calendar/blob/58ebc29369636f0dc19acd601e95af2ebb91446b/lib/cal_web/live/app_live.ex
+ [x] Create an `event` Struct that has all the fields necessary to create events on `Google Calendar` 
+ [x] Document the functions comprehensively
+ [x] Publish to hex.pm as `gcal`:  https://hex.pm/packages/gcal
<img width="839" alt="image" src="https://user-images.githubusercontent.com/194400/236341404-b61e614f-835f-47f6-9a6f-1caa8d52b955.png">

**Comment by nelsonic** [comment]
Done: https://hexdocs.pm/gcal/Gcal.html ✅
